import type { APIRoute } from 'astro';
import { SITE, CONTENT_TYPES, INDEX_THRESHOLDS } from '../config/site.config';
import { CATEGORIES } from '../config/categories';
import { AUTHORS } from '../config/authors';
import { getPublishedArticles, getAllTags, slugOf, type Article } from '../lib/articles';
import { getTools, getAgents, getPrompts, slugOfItem } from '../lib/directory';

/**
 * The site's sitemap, hand-built rather than generated by `@astrojs/sitemap`.
 *
 * Three reasons for owning it:
 *   1. One conventional `/sitemap.xml` URL, which is what people and SEO tools
 *      look for — not `sitemap-index.xml` pointing at a shard.
 *   2. Real per-item `lastmod` dates taken from front matter, instead of the
 *      build timestamp the integration stamps on every entry. A sitemap that
 *      claims every page changed at once is a sitemap crawlers learn to ignore.
 *   3. Only index-worthy URLs. Paginated archives past page 1 are `noindex`
 *      (see ArchiveLayout), thin category and tag archives are `noindex` below
 *      INDEX_THRESHOLDS, and `/search` is disallowed in robots.txt — listing any
 *      of them would contradict a directive we set elsewhere, and a sitemap that
 *      advertises noindexed URLs just burns crawl budget arguing with itself.
 *
 * Every URL is derived from the same collections and config the pages are built
 * from, so this cannot advertise a route that does not exist. When you add a new
 * route type, add it here.
 */

/** Matches `build.format: 'directory'` — every page URL ends in a slash. */
const abs = (path: string) => new URL(path, SITE.url).toString();

const iso = (date: Date) => date.toISOString().split('T')[0];

interface Entry {
  loc: string;
  lastmod?: string;
  changefreq: 'daily' | 'weekly' | 'monthly' | 'yearly';
  priority: number;
}

export const GET: APIRoute = async () => {
  const [articles, tags, tools, agents, prompts] = await Promise.all([
    getPublishedArticles(),
    getAllTags(),
    getTools(),
    getAgents(),
    getPrompts(),
  ]);

  /** Newest publish/update date in a set — the archive's honest lastmod. */
  const freshest = (list: Article[]): string | undefined => {
    if (!list.length) return undefined;
    const newest = list.reduce((max, a) => {
      const d = a.data.updatedDate ?? a.data.publishDate;
      return d > max ? d : max;
    }, new Date(0));
    return newest.valueOf() ? iso(newest) : undefined;
  };

  const siteLastmod = freshest(articles);
  const entries: Entry[] = [];

  // ---------- Home ----------
  entries.push({ loc: abs('/'), lastmod: siteLastmod, changefreq: 'daily', priority: 1.0 });

  // ---------- Content-type archives ----------
  for (const type of ['news', 'guide', 'review', 'comparison'] as const) {
    const list = articles.filter((a) => a.data.type === type);
    entries.push({
      // `href` already carries its trailing slash — appending another would
      // emit `/news//`, a URL that 301s and is not the canonical.
      loc: abs(CONTENT_TYPES[type].href),
      lastmod: freshest(list),
      changefreq: 'daily',
      priority: 0.9,
    });
  }
  entries.push({
    loc: abs('/articles/'),
    lastmod: siteLastmod,
    changefreq: 'daily',
    priority: 0.9,
  });

  // ---------- Directories and hubs ----------
  // `/authors/` belongs here rather than with the individual desk pages below:
  // it is the page a reader or a quality rater opens to answer "who is
  // responsible for this content", so it needs to be discoverable in its own
  // right, not only reachable from a byline.
  for (const hub of [
    '/tools/',
    '/agents/',
    '/prompts/',
    '/resources/',
    '/categories/',
    '/tags/',
    '/authors/',
  ]) {
    entries.push({ loc: abs(hub), lastmod: siteLastmod, changefreq: 'weekly', priority: 0.9 });
  }

  // ---------- Articles ----------
  for (const article of articles) {
    entries.push({
      loc: abs(`/articles/${slugOf(article)}/`),
      lastmod: iso(article.data.updatedDate ?? article.data.publishDate),
      changefreq: 'monthly',
      priority: article.data.featured ? 0.9 : 0.8,
    });
  }

  // ---------- Directory detail pages ----------
  for (const tool of tools) {
    entries.push({
      loc: abs(`/tools/${slugOfItem(tool)}/`),
      lastmod: tool.data.updatedDate ? iso(tool.data.updatedDate) : siteLastmod,
      changefreq: 'weekly',
      priority: 0.75,
    });
  }
  for (const agent of agents) {
    entries.push({
      loc: abs(`/agents/${slugOfItem(agent)}/`),
      lastmod: agent.data.updatedDate ? iso(agent.data.updatedDate) : siteLastmod,
      changefreq: 'weekly',
      priority: 0.75,
    });
  }
  for (const prompt of prompts) {
    entries.push({
      loc: abs(`/prompts/${slugOfItem(prompt)}/`),
      lastmod: iso(prompt.data.publishDate),
      changefreq: 'monthly',
      priority: 0.7,
    });
  }

  // ---------- Category archives ----------
  // Thin and empty categories are still built and still linked from /categories/
  // (see the category route) — they are simply `noindex` until they hold enough
  // to stand as a landing page, so submitting them here would contradict the
  // robots meta the page itself serves.
  for (const category of CATEGORIES) {
    const inCategory = articles.filter((a) => a.data.category === category.slug);
    if (inCategory.length < INDEX_THRESHOLDS.category) continue;
    entries.push({
      loc: abs(`/category/${category.slug}/`),
      lastmod: freshest(inCategory),
      changefreq: 'weekly',
      priority: 0.7,
    });
  }

  // ---------- Tag archives ----------
  // Same threshold rule as categories, at a higher bar: a tag matching one or
  // two articles is a label, not a topic hub worth ranking.
  for (const { tag } of tags) {
    const tagged = articles.filter((a) => a.data.tags.includes(tag));
    if (tagged.length < INDEX_THRESHOLDS.tag) continue;
    entries.push({
      loc: abs(`/tag/${tag}/`),
      lastmod: freshest(tagged),
      changefreq: 'weekly',
      priority: 0.4,
    });
  }

  // ---------- Author pages ----------
  // An author page earns its place as soon as it has a byline attached — the
  // page carries a real bio and credentials, so one article is enough.
  for (const author of AUTHORS) {
    const written = articles.filter((a) => a.data.author === author.slug);
    if (written.length < INDEX_THRESHOLDS.author) continue;
    entries.push({
      loc: abs(`/authors/${author.slug}/`),
      lastmod: freshest(written),
      changefreq: 'weekly',
      priority: 0.5,
    });
  }

  // ---------- Static pages ----------
  for (const page of [
    '/about/',
    '/contact/',
    '/editorial-policy/',
    '/privacy-policy/',
    '/terms/',
    '/cookie-policy/',
    '/disclaimer/',
  ]) {
    entries.push({ loc: abs(page), changefreq: 'yearly', priority: 0.3 });
  }

  // Guard against a route appearing twice if two rules ever overlap.
  const seen = new Set<string>();
  const unique = entries.filter((e) => (seen.has(e.loc) ? false : (seen.add(e.loc), true)));

  const body = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${unique
  .map(
    (e) =>
      `  <url><loc>${e.loc}</loc>${
        e.lastmod ? `<lastmod>${e.lastmod}</lastmod>` : ''
      }<changefreq>${e.changefreq}</changefreq><priority>${e.priority.toFixed(1)}</priority></url>`
  )
  .join('\n')}
</urlset>
`;

  return new Response(body, {
    headers: {
      'Content-Type': 'application/xml; charset=utf-8',
      'Cache-Control': 'public, max-age=3600',
    },
  });
};
